BOARD ?= nucleo-f446re

include ../Makefile.tests_common

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
USEMODULE += random
USEMODULE += fmt

USEMODULE += sx1302

include $(RIOTBASE)/Makefile.include
